name: fozminesproof-core
version: '@version@'
main: org.phantam.fozminesproofcore.FozmineSproofCore
api-version: "1.19"
description: Advanced fake player management system with minimal TPS impact
author: phantam
commands:
  sproof:
    description: Main command for the FozmineSproof fake player system.
    aliases:
      - fsproof
      - fakeplayers
      - fp
      - sproof
      - fplayer
      - fakeplayer
      - fozminesproof
    permission: fozminesproof.admin
    usage: /<command> [spawn|remove] <name>

permissions:
  fozminesproof.admin:
    description: Grants full access to all FozmineSproof commands.
    default: op