name: fozminespoof-core
version: '@version@'
main: org.phantam.fozminespoofcore.FozmineSpoofCore
api-version: "1.19"
description: Advanced fake player management system with minimal TPS impact
author: phantam
commands:
  spoof:
    description: Main command for the Fozminespoof fake player system.
    aliases:
      - fspoof
      - fakeplayers
      - fp
      - spoof
      - fplayer
      - fakeplayer
      - fozminespoof
    permission: fozminespoof.admin
    usage: /<command> [spawn|remove] <name>

permissions:
  fozminespoof.admin:
    description: Grants full access to all Fozminespoof commands.
    default: op